---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: contour-pre-reqs
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 1m0s
  path: ./base/utilites/contour/pre-reqs
  prune: false
  sourceRef:
    kind: GitRepository
    name: tmc-git-repo
    namespace: tanzu-continuousdelivery-resources